import type { Scholarship } from "@/types";

// Curated list of real scholarships for NYC high school students
const SCHOLARSHIP_DATABASE: Scholarship[] = [
  {
    id: "1",
    title: "Coca-Cola Scholars Program",
    amount: "$20,000",
    deadline: "October 31, 2025",
    description: "Achievement-based scholarship recognizing high school seniors for their leadership, service, and academic excellence.",
    eligibility: ["U.S. Citizen/Permanent Resident", "High school senior", "3.0+ GPA", "Demonstrate leadership"],
    url: "https://www.coca-colascholarsfoundation.org/apply/",
  },
  {
    id: "2",
    title: "Gates Scholarship",
    amount: "Full tuition",
    deadline: "September 15, 2025",
    description: "Highly selective scholarship for exceptional, low-income minority students to cover the full cost of college.",
    eligibility: ["Pell-eligible", "Minority student", "3.3+ GPA", "U.S. citizen or permanent resident"],
    url: "https://www.thegatesscholarship.org/scholarship",
  },
  {
    id: "3",
    title: "Jack Kent Cooke Foundation Scholarship",
    amount: "Up to $55,000/year",
    deadline: "November 14, 2025",
    description: "Supporting high-achieving students with financial need to attend the nation's best colleges.",
    eligibility: ["High academic achievement", "Financial need", "3.5+ GPA", "Leadership"],
    url: "https://www.jkcf.org/our-scholarships/college-scholarship-program/",
  },
  {
    id: "4",
    title: "Dell Scholars Program",
    amount: "$20,000",
    deadline: "December 1, 2025",
    description: "Scholarship for students who have overcome significant obstacles and demonstrate determination.",
    eligibility: ["Pell Grant eligible", "Participate in approved college readiness program", "2.4+ GPA"],
    url: "https://www.dellscholars.org/scholarship/",
  },
  {
    id: "5",
    title: "QuestBridge National College Match",
    amount: "Full ride to partner colleges",
    deadline: "September 26, 2025",
    description: "Connects high-achieving, low-income students with full four-year scholarships to partner colleges.",
    eligibility: ["Low income", "High academic achievement", "U.S. citizen or permanent resident"],
    url: "https://www.questbridge.org/high-school-students/national-college-match",
  },
  {
    id: "6",
    title: "Ron Brown Scholar Program",
    amount: "$40,000",
    deadline: "January 9, 2026",
    description: "Scholarship for African American high school seniors demonstrating academic excellence and community engagement.",
    eligibility: ["African American", "U.S. citizen or permanent resident", "Strong academics", "Community service"],
    url: "https://www.ronbrown.org/apply",
  },
  {
    id: "7",
    title: "Burger King Scholars Program",
    amount: "$1,000 - $60,000",
    deadline: "December 15, 2025",
    description: "Recognizing students for their academic accomplishments, work experience, community service, and financial need.",
    eligibility: ["High school senior", "U.S. or Canadian resident", "2.5+ GPA", "Work experience"],
    url: "https://www.scholarsapply.org/burgerkingscholars/",
  },
  {
    id: "8",
    title: "Elks National Foundation Most Valuable Student",
    amount: "$4,000 - $50,000",
    deadline: "November 5, 2025",
    description: "Merit-based scholarship rewarding students for scholarship, leadership, and financial need.",
    eligibility: ["U.S. citizen", "High school senior", "Financial need", "Leadership"],
    url: "https://www.elks.org/scholars/scholarships/mvs.cfm",
  },
  {
    id: "9",
    title: "AXA Achievement Scholarship",
    amount: "$2,500 - $25,000",
    deadline: "December 15, 2025",
    description: "Scholarship for students who have demonstrated ambition and drive in school, community, and workplace.",
    eligibility: ["U.S. citizen or legal resident", "High school senior", "Demonstrate achievement"],
    url: "https://www.axa.com/en/about-axa/axa-achievement-scholarship",
  },
  {
    id: "10",
    title: "Hispanic Scholarship Fund",
    amount: "$500 - $5,000",
    deadline: "February 15, 2026",
    description: "Supporting Hispanic American students pursuing higher education.",
    eligibility: ["Hispanic heritage", "U.S. citizen or legal resident", "3.0+ GPA", "Enrolled in college"],
    url: "https://www.hsf.net/scholarship",
  },
  {
    id: "11",
    title: "Horatio Alger Scholarship",
    amount: "$25,000",
    deadline: "October 25, 2025",
    description: "For students who have overcome adversity and demonstrate financial need.",
    eligibility: ["Financial need", "2.0+ GPA", "U.S. citizen", "Involved in community service"],
    url: "https://scholars.horatioalger.org/scholarships/",
  },
  {
    id: "12",
    title: "UNCF General Scholarship",
    amount: "Varies",
    deadline: "Rolling",
    description: "Supporting African American students attending UNCF member institutions and beyond.",
    eligibility: ["African American", "Financial need", "Academic achievement"],
    url: "https://opportunities.uncf.org/",
  },
  {
    id: "13",
    title: "Davidson Fellows Scholarship",
    amount: "$10,000 - $50,000",
    deadline: "February 13, 2026",
    description: "Recognizing students who have completed significant work in STEM, literature, music, or philosophy.",
    eligibility: ["Under 18 years old", "U.S. citizen or permanent resident", "Significant project"],
    url: "https://www.davidsongifted.org/gifted-programs/fellows-scholarship/",
  },
  {
    id: "14",
    title: "Dream.US National Scholarship",
    amount: "Up to $33,000",
    deadline: "February 28, 2026",
    description: "For DREAMers who came to the U.S. as children and want to pursue higher education.",
    eligibility: ["DACA or TPS eligible", "Financial need", "3.0+ GPA"],
    url: "https://www.thedream.us/scholarships/national-scholarship/",
  },
  {
    id: "15",
    title: "Google Lime Scholarship",
    amount: "$10,000",
    deadline: "December 12, 2025",
    description: "For students with disabilities pursuing computer science or related technical field.",
    eligibility: ["Disability", "Computer science major", "Strong academic record"],
    url: "https://www.limeconnect.com/programs/page/google-lime-scholarship",
  },
  {
    id: "16",
    title: "APIASF Scholarship",
    amount: "$2,500 - $20,000",
    deadline: "January 10, 2026",
    description: "Supporting Asian and Pacific Islander American students with financial need.",
    eligibility: ["Asian or Pacific Islander heritage", "U.S. citizen or permanent resident", "2.7+ GPA"],
    url: "https://www.apiasf.org/scholarship.html",
  },
  {
    id: "17",
    title: "Foot Locker Scholar Athletes Program",
    amount: "$20,000",
    deadline: "December 17, 2025",
    description: "For student-athletes who demonstrate strong academic achievement and athletic excellence.",
    eligibility: ["High school senior", "Varsity athlete", "3.0+ GPA", "Community service"],
    url: "https://www.footlockerscholarathletes.com/",
  },
  {
    id: "18",
    title: "Voice of Democracy Scholarship",
    amount: "$1,000 - $30,000",
    deadline: "October 31, 2025",
    description: "Audio-essay scholarship program for students to express their views on democracy.",
    eligibility: ["Grades 9-12", "U.S. citizen or permanent resident", "Submit audio essay"],
    url: "https://www.vfw.org/community/youth-and-education/youth-scholarships",
  },
  {
    id: "19",
    title: "Prudential Spirit of Community Awards",
    amount: "$1,000 - $5,000",
    deadline: "November 5, 2025",
    description: "Honoring students for outstanding volunteer service in their communities.",
    eligibility: ["Grades 5-12", "Volunteer service", "U.S. resident"],
    url: "https://spirit.prudential.com/",
  },
  {
    id: "20",
    title: "NSHSS Foundation STEM Scholarship",
    amount: "$1,000",
    deadline: "March 15, 2026",
    description: "Supporting students pursuing degrees in science, technology, engineering, or mathematics.",
    eligibility: ["NSHSS member", "3.0+ GPA", "STEM major"],
    url: "https://www.nshss.org/scholarships/",
  },
  {
    id: "21",
    title: "Scholly Search Scholarship",
    amount: "$500 - $10,000",
    deadline: "Rolling",
    description: "Various scholarships available through the Scholly platform for students based on different criteria.",
    eligibility: ["Varies by scholarship", "High school or college student"],
    url: "https://myscholly.com/",
  },
  {
    id: "22",
    title: "Scholarship America Dream Award",
    amount: "$5,000 - $15,000",
    deadline: "February 7, 2026",
    description: "Renewable scholarships for students entering their second year or higher of postsecondary education.",
    eligibility: ["Completed first year of college", "Unmet financial need", "2.5+ GPA"],
    url: "https://scholarshipamerica.org/students/browse-scholarships/",
  },
  {
    id: "23",
    title: "Blacks at Microsoft Scholarship",
    amount: "$5,000",
    deadline: "January 31, 2026",
    description: "For Black and African American students pursuing degrees in engineering, computer science, or related STEM fields.",
    eligibility: ["Black/African American", "STEM major", "Enrolled in college"],
    url: "https://careers.microsoft.com/us/en/usuniversityscholarship",
  },
  {
    id: "24",
    title: "Generation Google Scholarship",
    amount: "$10,000",
    deadline: "December 4, 2025",
    description: "For students from underrepresented groups pursuing computer science degrees.",
    eligibility: ["Underrepresented minority", "Computer science major", "Strong academic record"],
    url: "https://buildyourfuture.withgoogle.com/scholarships/generation-google-scholarship",
  },
  {
    id: "25",
    title: "P.E.O. Program for Continuing Education",
    amount: "$3,000",
    deadline: "Rolling",
    description: "Grants for women whose education was interrupted and are returning to complete a degree.",
    eligibility: ["Female", "Returning to education", "U.S. or Canadian citizen"],
    url: "https://www.peointernational.org/pce-eligibility-requirements",
  },
  {
    id: "26",
    title: "Jeannette Rankin Women's Scholarship",
    amount: "$2,000",
    deadline: "March 1, 2026",
    description: "For low-income women ages 35 and older pursuing a technical or vocational education.",
    eligibility: ["Women 35+", "Low income", "Technical/vocational education"],
    url: "https://rankinfoundation.org/students/eligibility/",
  },
  {
    id: "27",
    title: "APIA Scholarship",
    amount: "$2,500 - $20,000",
    deadline: "January 15, 2026",
    description: "For Asian & Pacific Islander American students with financial need and academic achievement.",
    eligibility: ["APIA heritage", "U.S. citizen or permanent resident", "2.7+ GPA", "Financial need"],
    url: "https://www.apiasf.org/scholarship.html",
  },
  {
    id: "28",
    title: "American Indian College Fund Scholarship",
    amount: "Varies",
    deadline: "May 31, 2026",
    description: "Supporting American Indian and Alaska Native students attending accredited institutions.",
    eligibility: ["Native American/Alaska Native heritage", "Enrolled tribal member", "Accredited institution"],
    url: "https://collegefund.org/students/scholarships/",
  },
  {
    id: "29",
    title: "Point Foundation Scholarship",
    amount: "$10,000 - $36,000",
    deadline: "January 27, 2026",
    description: "For LGBTQ students who have been leaders in their communities.",
    eligibility: ["LGBTQ", "U.S. citizen or permanent resident", "Leadership experience"],
    url: "https://pointfoundation.org/point-apply/",
  },
  {
    id: "30",
    title: "Women Techmakers Scholars Program",
    amount: "$10,000",
    deadline: "December 11, 2025",
    description: "Google scholarship for women in computer science and gaming.",
    eligibility: ["Female", "Computer science or gaming major", "Strong academic record"],
    url: "https://www.womentechmakers.com/scholars",
  },
  {
    id: "31",
    title: "Society of Women Engineers Scholarship",
    amount: "$1,000 - $15,000",
    deadline: "February 15, 2026",
    description: "Supporting women studying engineering and related fields.",
    eligibility: ["Female", "Engineering major", "SWE member preferred"],
    url: "https://scholarships.swe.org/",
  },
  {
    id: "32",
    title: "UNCF STEM Scholars Program",
    amount: "$5,000",
    deadline: "December 31, 2025",
    description: "For African American students majoring in STEM fields.",
    eligibility: ["African American", "STEM major", "3.0+ GPA", "Financial need"],
    url: "https://opportunities.uncf.org/",
  },
  {
    id: "33",
    title: "Nordstrom Scholarship",
    amount: "$2,500 - $10,000",
    deadline: "May 1, 2026",
    description: "For students who work and have high academic achievement in states where Nordstrom operates.",
    eligibility: ["Work experience", "Live in eligible states", "Strong grades"],
    url: "https://nordstromscholarship.org/",
  },
  {
    id: "34",
    title: "Kiwanis Scholarship",
    amount: "$1,000 - $5,000",
    deadline: "Varies by club",
    description: "Local scholarships offered by Kiwanis clubs for students in their communities.",
    eligibility: ["Varies by local club", "Community involvement"],
    url: "https://www.kiwanis.org/scholarships",
  },
  {
    id: "35",
    title: "Amazon Future Engineer Scholarship",
    amount: "$40,000",
    deadline: "January 13, 2026",
    description: "For students from underrepresented and underserved communities pursuing computer science.",
    eligibility: ["High school senior", "Computer science major", "U.S. citizen or DACA"],
    url: "https://www.amazonfutureengineer.com/scholarships",
  },
  {
    id: "36",
    title: "Comcast Leaders and Achievers Scholarship",
    amount: "$2,500",
    deadline: "December 13, 2025",
    description: "For students demonstrating strong commitment to community service and academics.",
    eligibility: ["High school senior", "Community service", "Comcast service area"],
    url: "https://corporate.comcast.com/impact/education/youth-education-leadership",
  },
  {
    id: "37",
    title: "Best Buy Scholarship",
    amount: "$1,000 - $10,000",
    deadline: "February 15, 2026",
    description: "For students planning to pursue a technology-focused degree.",
    eligibility: ["High school senior", "Tech-related major", "Community involvement"],
    url: "https://corporate.bestbuy.com/community-grants-scholarships/",
  },
  {
    id: "38",
    title: "LEAGUE Foundation Academic Scholarship",
    amount: "$2,500 - $10,000",
    deadline: "April 25, 2026",
    description: "For LGBTQ+ students and allies demonstrating leadership and community involvement.",
    eligibility: ["LGBTQ+ or ally", "Community involvement", "Academic achievement"],
    url: "https://leaguefoundation.org/scholarships/",
  },
  {
    id: "39",
    title: "NYC Merit Scholarship",
    amount: "Full tuition",
    deadline: "Varies",
    description: "NYC program providing free tuition at CUNY or SUNY for eligible NYC students.",
    eligibility: ["NYC resident", "Income under $125,000", "Enroll at CUNY/SUNY"],
    url: "https://www.hesc.ny.gov/pay-for-college/apply-for-financial-aid/nys-grants-scholarships-awards/the-excelsior-scholarship.html",
  },
  {
    id: "40",
    title: "NYC Department of Youth Scholarship",
    amount: "Varies",
    deadline: "Spring 2026",
    description: "Scholarships for NYC youth involved in community programs.",
    eligibility: ["NYC resident", "Community program involvement"],
    url: "https://www.nyc.gov/site/dycd/services/scholarships.page",
  },
];

export function getScholarships(page: number = 1, perPage: number = 6): { scholarships: Scholarship[], hasMore: boolean, total: number } {
  const startIndex = (page - 1) * perPage;
  const endIndex = startIndex + perPage;
  const scholarships = SCHOLARSHIP_DATABASE.slice(startIndex, endIndex);
  
  return {
    scholarships,
    hasMore: endIndex < SCHOLARSHIP_DATABASE.length,
    total: SCHOLARSHIP_DATABASE.length,
  };
}

export function getAllScholarships(): Scholarship[] {
  return SCHOLARSHIP_DATABASE;
}
